# Generated by Django 4.2.1 on 2023-05-20 11:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_rename_blog_publication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="publication",
            old_name="update_at",
            new_name="updated_at",
        ),
    ]
